# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [28]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

array_weight = np.array(weight)
array_height = np.array(height)
height_squared = array_height**2
weight_over_height = array_weight / height_squared
bmi = weight_over_height * 730
print(bmi)

[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [45]:
import numpy as np

#basic
def make_matrix(int_1, int_2):
    print(np.random.uniform(int_1, int_2, (3,3)))
    
make_matrix(3, 8)
print("\n")

#extra
def fancy_matrix(int_1, int_2, rows, columns, data_type):
    m = np.random.uniform(int_1, int_2, (rows, columns))
    m = m.astype(data_type)
    print(m)
    
fancy_matrix(0, 10, 4, 4, "int32")

[[3.55663511 7.67006035 3.58642921]
 [6.21948348 6.69014818 7.36826566]
 [4.5195224  6.07343743 6.20004188]]


[[2 0 8 0]
 [2 6 0 1]
 [5 9 2 4]
 [1 4 9 5]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [ ]:
import csv
import numpy as np




In [50]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1, usecols = np.arange(0,24), invalid_raise=False, names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('redsox_2017_hitting.txt')
bs2018 = load_data('redsox_2018_hitting.txt')

diff_slg = sum(bs2017["SLG"]) - sum(bs2018["SLG"])
print(f"Difference between 2017 and 2018 SLG: {diff_slg}")

if sum(bs2017["SLG"]) > sum(bs2018["SLG"]):
    print("2017 was a better year based on SLG")
else:
    print("2018 was a better year based on SLG")

Difference between 2017 and 2018 SLG: 1.296999879181385
2017 was a better year based on SLG
